### ISSUE TITLE
urls 추가 및 views 구현 (소셜로그인 시나리오 협의)

### ISSUE THREAD

**Issue by idle-danie** [wanted-cloneproject/Wanted-Clone-BE#1]
- [x]  소셜로그인 제외 urls 추가 및 views 구현
- [x] 로그인 시나리오 협의

**Comment by idle-danie** [comment]
## 추가 요청사항

1. DNS서버에 사용될 도메인 네임 (ex: wantedclone.com) 정해야 합니다 😊  (필수)
2. 404에러 페이지 간단하게 하나 구현해야 합니다 🤔 (선택)

**Comment by gkfla668** [comment]
1. 현재 메인과 이력서 페이지, AI 합격예측 페이지, 로그인 페이지가 있습니다!
**메인**: wanted-clone/
**이력서**: wanted-clone/cv
**AI 합격예측**: wanted-clone/ai
**로그인**: wanted-clone/login

2. 아래와 같이 로그인 성공 유무를 boolean 값으로 판별하여 사용자 아이콘 클릭했을 때 모달창 띄우는 정도면 괜찮을 것 같아요!
![image](https://github.com/wanted-cloneproject/Wanted-Clone-BE/assets/81246338/09bbbb65-5a92-45af-929b-d35d977c19c8)

---

### 추가 요청 사항

1. 깃허브로 배포하는 법도 있는데 어떨까요? ex) _http://{사용자 이름}.github.io/{저장소 이름}_ 
2. 🆗👍

**Comment by idle-danie** [comment]
All solved
